REM dynamically generated by XartaBackupvbs
"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysqldump.exe" --defaults-extra-file=F:\sql\prog\my.cnf --verbose -udump -hlocalhost hmailserver 2> G:\mysql_dump\dump.log > %1
"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysqlcheck.exe" --defaults-extra-file=F:\sql\prog\my.cnf --verbose -uhMailServer --repair --databases hmailserver
